name: ci
on:
  workflow_dispatch: {}
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      docs-only: ${{ steps.filter.outputs.docs_count == steps.filter.outputs.all_count
        }}
      docs: ${{ steps.filter.outputs.docs }}
      go: ${{ steps.filter.outputs.go }}
      site: ${{ steps.filter.outputs.site }}
      k8s: ${{ steps.filter.outputs.k8s }}
      ci: ${{ steps.filter.outputs.ci }}
      db: ${{ steps.filter.outputs.db }}
      gomod: ${{ steps.filter.outputs.gomod }}
      offlinedocs-only: ${{ steps.filter.outputs.offlinedocs_count == steps.filter.outputs.all_count
        }}
      offlinedocs: ${{ steps.filter.outputs.offlinedocs }}
      tailnet-integration: ${{ steps.filter.outputs.tailnet-integration }}
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e
      with:
        egress-policy: audit
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        fetch-depth: 1
        persist-credentials: false
    - name: check changed files
      uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
      id: filter
      with:
        filters: "all:\n  - \"**\"\ndocs:\n  - \"docs/**\"\n  - \"README.md\"\n  -\
          \ \"examples/web-server/**\"\n  - \"examples/monitoring/**\"\n  - \"examples/lima/**\"\
          \ndb:\n  - \"**.sql\"\n  - \"coderd/database/**\"\ngo:\n  - \"**.sql\"\n\
          \  - \"**.go\"\n  - \"**.golden\"\n  - \"go.mod\"\n  - \"go.sum\"\n  # Other\
          \ non-Go files that may affect Go code:\n  - \"**.rego\"\n  - \"**.sh\"\n\
          \  - \"**.tpl\"\n  - \"**.gotmpl\"\n  - \"**.gotpl\"\n  - \"Makefile\"\n\
          \  - \"site/static/error.html\"\n  # Main repo directories for completeness\
          \ in case other files are\n  # touched:\n  - \"agent/**\"\n  - \"cli/**\"\
          \n  - \"cmd/**\"\n  - \"coderd/**\"\n  - \"enterprise/**\"\n  - \"examples/**\"\
          \n  - \"helm/**\"\n  - \"provisioner/**\"\n  - \"provisionerd/**\"\n  -\
          \ \"provisionersdk/**\"\n  - \"pty/**\"\n  - \"scaletest/**\"\n  - \"tailnet/**\"\
          \n  - \"testutil/**\"\ngomod:\n  - \"go.mod\"\n  - \"go.sum\"\nsite:\n \
          \ - \"site/**\"\nk8s:\n  - \"helm/**\"\n  - \"scripts/Dockerfile\"\n  -\
          \ \"scripts/Dockerfile.base\"\n  - \"scripts/helm.sh\"\nci:\n  - \".github/actions/**\"\
          \n  - \".github/workflows/ci.yaml\"\nofflinedocs:\n  - \"offlinedocs/**\"\
          \ntailnet-integration:\n  - \"tailnet/**\"\n  - \"go.mod\"\n  - \"go.sum\"\
          \n"
    - id: debug
      run: 'echo "$FILTER_JSON"

        '
      env:
        FILTER_JSON: ${{ toJSON(steps.filter.outputs) }}
  lint:
    needs: changes
    if: needs.changes.outputs.offlinedocs-only == 'false' || needs.changes.outputs.ci
      == 'true' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e
      with:
        egress-policy: audit
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        fetch-depth: 1
        persist-credentials: false
    - name: Setup Node
      uses: ./.github/actions/setup-node
    - name: Setup Go
      uses: ./.github/actions/setup-go
    - name: Get golangci-lint cache dir
      run: 'linter_ver=$(grep -Eo ''GOLANGCI_LINT_VERSION=\S+'' dogfood/coder/Dockerfile
        | cut -d ''='' -f 2)

        ./.github/scripts/retry.sh -- go install "github.com/golangci/golangci-lint/cmd/golangci-lint@v$linter_ver"

        dir=$(golangci-lint cache status | awk ''/Dir/ { print $2 }'')

        echo "LINT_CACHE_DIR=$dir" >> "$GITHUB_ENV"

        '
    - name: golangci-lint cache
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306
      with:
        path: '${{ env.LINT_CACHE_DIR }}

          '
        key: golangci-lint-${{ runner.os }}-${{ hashFiles('**/*.go') }}
        restore-keys: 'golangci-lint-${{ runner.os }}-

          '
    - name: Check for typos
      uses: crate-ci/typos@2d0ce569feab1f8752f1dde43cc2f2aa53236e06
      with:
        config: .github/workflows/typos.toml
    - name: Fix the typos
      if: ${{ failure() }}
      run: 'echo "::notice:: you can automatically fix typos from your CLI:

        cargo install typos-cli

        typos -c .github/workflows/typos.toml -w"

        '
    - name: Install helm
      uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4
      with:
        version: v3.9.2
      continue-on-error: true
      id: setup-helm
    - name: Install helm (fallback)
      if: steps.setup-helm.outcome == 'failure'
      run: 'set -euo pipefail

        curl -fsSL https://packages.buildkite.com/helm-linux/helm-debian/gpgkey |
        gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null

        echo "deb [signed-by=/usr/share/keyrings/helm.gpg] https://packages.buildkite.com/helm-linux/helm-debian/any/
        any main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list

        sudo apt-get update

        sudo apt-get install -y helm=3.9.2-1

        '
    - name: Verify helm version
      run: helm version --short
    - name: make lint
      run: make --output-sync=line -j lint
    - name: Check workflow files
      run: 'bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        1.7.4

        ./actionlint -color -shellcheck= -ignore "set-output"

        '
      shell: bash
    - name: Check for unstaged files
      run: 'rm -f ./actionlint ./typos

        ./scripts/check_unstaged.sh

        '
      shell: bash
  lint-actions:
    needs: changes
    if: needs.changes.outputs.ci == 'true'
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e
      with:
        egress-policy: audit
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        fetch-depth: 1
        persist-credentials: false
    - name: Setup Go
      uses: ./.github/actions/setup-go
    - name: make lint/actions
      run: make --output-sync=line -j lint/actions
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  gen:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e
      with:
        egress-policy: audit
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        fetch-depth: 1
        persist-credentials: false
    - name: Setup Node
      uses: ./.github/actions/setup-node
    - name: Setup Go
      uses: ./.github/actions/setup-go
    - name: Setup sqlc
      uses: ./.github/actions/setup-sqlc
    - name: Setup Terraform
      uses: ./.github/actions/setup-tf
    - name: go install tools
      uses: ./.github/actions/setup-go-tools
    - name: Install Protoc
      run: 'mkdir -p /tmp/proto

        pushd /tmp/proto

        curl -L -o protoc.zip https://github.com/protocolbuffers/protobuf/releases/download/v23.4/protoc-23.4-linux-x86_64.zip

        unzip protoc.zip

        sudo cp -r ./bin/* /usr/local/bin

        sudo cp -r ./include /usr/local/bin/include

        popd

        '
    - name: make gen
      timeout-minutes: 8
      run: '# Remove golden files to detect discrepancy in generated files.

        make clean/golden-files

        # Notifications require DB, we could start a DB instance here but

        # let''s just restore for now.

        git checkout -- coderd/notifications/testdata/rendered-templates

        # no `-j` flag as `make` fails with:

        # coderd/rbac/object_gen.go:1:1: syntax error: package statement must be first

        make --output-sync -B gen

        '
    - name: Check for unstaged files
      run: ./scripts/check_unstaged.sh
  fmt:
    needs: changes
    if: needs.changes.outputs.offlinedocs-only == 'false' || needs.changes.outputs.ci
      == 'true' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e
      with:
        egress-policy: audit
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        fetch-depth: 1
        persist-credentials: false
    - name: Setup Node
      uses: ./.github/actions/setup-node
    - name: Check Go version
      run: IGNORE_NIX=true ./scripts/check_go_versions.sh
    - name: Setup Go
      uses: ./.github/actions/setup-go
    - name: Install shfmt
      run: ./.github/scripts/retry.sh -- go install mvdan.cc/sh/v3/cmd/shfmt@v3.7.0
    - name: make fmt
      timeout-minutes: 7
      run: "PATH=\"${PATH}:$(go env GOPATH)/bin\" \\\n  make --output-sync -j -B fmt\n"
    - name: Check for unstaged files
      run: ./scripts/check_unstaged.sh
  test-go-pg:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.go == 'true' || needs.changes.outputs.ci == 'true' ||
      github.ref == 'refs/heads/main'
    timeout-minutes: 25
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-2022
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e
      with:
        egress-policy: audit
    - name: Disable Spotlight Indexing
      if: runner.os == 'macOS'
      run: "enabled=$(sudo mdutil -a -s | { grep -Fc \"Indexing enabled\" || true;\
        \ })\nif [ \"$enabled\" -eq 0 ]; then\n  echo \"Spotlight indexing is already\
        \ disabled\"\n  exit 0\nfi\nsudo mdutil -a -i off\nsudo mdutil -X /\nsudo\
        \ launchctl bootout system /System/Library/LaunchDaemons/com.apple.metadata.mds.plist\n"
    - name: Setup RAM Disks
      if: runner.os == 'Windows'
      uses: coder/setup-ramdisk-action@e1100847ab2d7bcd9d14bcda8f2d1b0f07b36f1b
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        fetch-depth: 1
        persist-credentials: false
    - name: Setup Go Paths
      id: go-paths
      uses: ./.github/actions/setup-go-paths
    - name: Setup GNU tools (macOS)
      uses: ./.github/actions/setup-gnu-tools
    - name: Setup Go
      uses: ./.github/actions/setup-go
      with:
        use-preinstalled-go: ${{ runner.os == 'Windows' }}
        use-cache: true
    - name: Setup Terraform
      uses: ./.github/actions/setup-tf
    - name: Download Test Cache
      id: download-cache
      uses: ./.github/actions/test-cache/download
      with:
        key-prefix: test-go-pg-${{ runner.os }}-${{ runner.arch }}
    - name: Setup Embedded Postgres Cache Paths
      id: embedded-pg-cache
      uses: ./.github/actions/setup-embedded-pg-cache-paths
    - name: Download Embedded Postgres Cache
      id: download-embedded-pg-cache
      uses: ./.github/actions/embedded-pg-cache/download
      with:
        key-prefix: embedded-pg-${{ runner.os }}-${{ runner.arch }}
        cache-path: ${{ steps.embedded-pg-cache.outputs.cached-dirs }}
    - name: Normalize File and Directory Timestamps
      shell: bash
      run: 'find . -type f ! -path ./.git/\*\* | mtimehash

        find . -type d ! -path ./.git/\*\* -exec touch -t 200601010000 {} +

        '
    - name: Normalize Terraform Path for Caching
      shell: bash
      run: 'mkdir -p "$RUNNER_TEMP/sym"

        source scripts/normalize_path.sh

        normalize_path_with_symlinks "$RUNNER_TEMP/sym" "$(dirname "$(which terraform)")"

        '
    - name: Setup RAM disk for Embedded Postgres (Windows)
      if: runner.os == 'Windows'
      shell: bash
      run: mkdir -p "R:/temp/embedded-pg"
    - name: Setup RAM disk for Embedded Postgres (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: '# Postgres runs faster on a ramdisk on macOS.

        mkdir -p /tmp/tmpfs

        sudo mount_tmpfs -o noowners -s 8g /tmp/tmpfs


        # Install google-chrome for scaletests.

        # As another concern, should we really have this kind of external dependency

        # requirement on standard CI?

        brew install google-chrome


        # macOS will output "The default interactive shell is now zsh" intermittently
        in CI.

        touch ~/.bash_profile && echo "export BASH_SILENCE_DEPRECATION_WARNING=1"
        >> ~/.bash_profile

        '
    - name: Increase PTY limit (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: '# Increase PTY limit to avoid exhaustion during tests.

        # Default is 511; 999 is the maximum value on CI runner.

        sudo sysctl -w kern.tty.ptmx_max=999

        '
    - name: Test with PostgreSQL Database (Linux)
      if: runner.os == 'Linux'
      uses: ./.github/actions/test-go-pg
      with:
        postgres-version: '13'
        test-parallelism-packages: '8'
        test-parallelism-tests: '8'
        test-count: ${{ github.ref == 'refs/heads/main' && '1' || '' }}
    - name: Test with PostgreSQL Database (macOS)
      if: runner.os == 'macOS'
      uses: ./.github/actions/test-go-pg
      with:
        postgres-version: '13'
        test-parallelism-packages: '8'
        test-parallelism-tests: '16'
        test-count: ${{ github.ref == 'refs/heads/main' && '1' || '' }}
        test-packages: ./cli/... ./enterprise/cli/... ./agent/...
        embedded-pg-path: /tmp/tmpfs/embedded-pg
        embedded-pg-cache: ${{ steps.embedded-pg-cache.outputs.embedded-pg-cache }}
    - name: Test with PostgreSQL Database (Windows)
      if: runner.os == 'Windows'
      uses: ./.github/actions/test-go-pg
      with:
        postgres-version: '13'
        test-parallelism-packages: '8'
        test-parallelism-tests: '16'
        test-count: ${{ github.ref == 'refs/heads/main' && '1' || '' }}
        test-packages: ./cli/... ./enterprise/cli/... ./agent/...
        embedded-pg-path: R:/temp/embedded-pg
        embedded-pg-cache: ${{ steps.embedded-pg-cache.outputs.embedded-pg-cache }}
    - name: Upload failed test db dumps
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
      with:
        name: failed-test-db-dump-${{matrix.os}}
        path: '**/*.test.sql'
    - name: Upload Test Cache
      uses: ./.github/actions/test-cache/upload
      with:
        cache-key: ${{ steps.download-cache.outputs.cache-key }}
    - name: Upload Embedded Postgres Cache
      uses: ./.github/actions/embedded-pg-cache/upload
      if: runner.OS == 'macOS' || runner.OS == 'Windows'
      with:
        cache-key: ${{ steps.download-embedded-pg-cache.outputs.cache-key }}
        cache-path: ${{ steps.embedded-pg-cache.outputs.embedded-pg-cache }}
    - name: Upload test stats to Datadog
      timeout-minutes: 1
      continue-on-error: true
      uses: ./.github/actions/upload-datadog
      if: success() || failure()
      with:
        api-key: ${{ secrets.DATADOG_API_KEY }}
  test-go-pg-17:
    runs-on: ubuntu-latest
    needs:
    - changes
    if: needs.changes.outputs.go == 'true' || needs.changes.outputs.ci == 'true' ||
      github.ref == 'refs/heads/main'
    timeout-minutes: 25
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e
      with:
        egress-policy: audit
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        fetch-depth: 1
        persist-credentials: false
    - name: Setup Go
      uses: ./.github/actions/setup-go
    - name: Setup Terraform
      uses: ./.github/actions/setup-tf
    - name: Download Test Cache
      id: download-cache
      uses: ./.github/actions/test-cache/download
      with:
        key-prefix: test-go-pg-17-${{ runner.os }}-${{ runner.arch }}
    - name: Normalize Terraform Path for Caching
      shell: bash
      run: 'mkdir -p "$RUNNER_TEMP/sym"

        source scripts/normalize_path.sh

        normalize_path_with_symlinks "$RUNNER_TEMP/sym" "$(dirname "$(which terraform)")"

        '
    - name: Test with PostgreSQL Database
      uses: ./.github/actions/test-go-pg
      with:
        postgres-version: '17'
        test-parallelism-packages: '8'
        test-parallelism-tests: '8'
        test-count: ${{ github.ref == 'refs/heads/main' && '1' || '' }}
    - name: Upload Test Cache
      uses: ./.github/actions/test-cache/upload
      with:
        cache-key: ${{ steps.download-cache.outputs.cache-key }}
    - name: Upload test stats to Datadog
      timeout-minutes: 1
      continue-on-error: true
      uses: ./.github/actions/upload-datadog
      if: success() || failure()
      with:
        api-key: ${{ secrets.DATADOG_API_KEY }}
  test-go-race-pg:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.go == 'true' || needs.changes.outputs.ci == 'true' ||
      github.ref == 'refs/heads/main'
    timeout-minutes: 25
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e
      with:
        egress-policy: audit
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        fetch-depth: 1
        persist-credentials: false
    - name: Setup Go
      uses: ./.github/actions/setup-go
    - name: Setup Terraform
      uses: ./.github/actions/setup-tf
    - name: Download Test Cache
      id: download-cache
      uses: ./.github/actions/test-cache/download
      with:
        key-prefix: test-go-race-pg-${{ runner.os }}-${{ runner.arch }}
    - name: Normalize Terraform Path for Caching
      shell: bash
      run: 'mkdir -p "$RUNNER_TEMP/sym"

        source scripts/normalize_path.sh

        normalize_path_with_symlinks "$RUNNER_TEMP/sym" "$(dirname "$(which terraform)")"

        '
    - name: Run Tests
      uses: ./.github/actions/test-go-pg
      with:
        postgres-version: '17'
        test-parallelism-packages: '4'
        test-parallelism-tests: '4'
        race-detection: true
    - name: Upload Test Cache
      uses: ./.github/actions/test-cache/upload
      with:
        cache-key: ${{ steps.download-cache.outputs.cache-key }}
    - name: Upload test stats to Datadog
      timeout-minutes: 1
      continue-on-error: true
      uses: ./.github/actions/upload-datadog
      if: always()
      with:
        api-key: ${{ secrets.DATADOG_API_KEY }}
  test-go-tailnet-integration:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.tailnet-integration == 'true' || needs.changes.outputs.ci
      == 'true'
    timeout-minutes: 20
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e
      with:
        egress-policy: audit
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        fetch-depth: 1
        persist-credentials: false
    - name: Setup Go
      uses: ./.github/actions/setup-go
    - name: Install Nginx
      run: sudo apt-get update && sudo apt-get install -y nginx
    - name: Run Tests
      run: make test-tailnet-integration
  test-js:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.site == 'true' || needs.changes.outputs.ci == 'true'
      || github.ref == 'refs/heads/main'
    timeout-minutes: 20
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e
      with:
        egress-policy: audit
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        fetch-depth: 1
        persist-credentials: false
    - name: Setup Node
      uses: ./.github/actions/setup-node
    - run: pnpm test:ci --max-workers "$(nproc)"
      working-directory: site
  test-e2e:
    runs-on: ubuntu-latest
    needs: changes
    strategy:
      fail-fast: false
      matrix:
        variant:
        - premium: false
          name: test-e2e
    if: (needs.changes.outputs.go == 'true' || needs.changes.outputs.site == 'true'
      || needs.changes.outputs.ci == 'true' || github.ref == 'refs/heads/main') &&
      !(github.event.pull_request.head.repo.fork)
    timeout-minutes: 20
    name: ${{ matrix.variant.name }}
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e
      with:
        egress-policy: audit
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        fetch-depth: 1
        persist-credentials: false
    - name: Setup Node
      uses: ./.github/actions/setup-node
    - name: Setup Go
      uses: ./.github/actions/setup-go
    - run: make gen/mark-fresh
      name: make gen
    - run: make site/e2e/bin/coder
      name: make coder
    - run: pnpm build
      env:
        NODE_OPTIONS: ${{ github.repository_owner == 'coder' && '--max_old_space_size=8192'
          || '' }}
      working-directory: site
    - run: pnpm playwright:install
      working-directory: site
    - run: pnpm playwright:test --forbid-only --workers 1
      if: ${{ !matrix.variant.premium }}
      env:
        DEBUG: pw:api
      working-directory: site
    - run: pnpm playwright:test --forbid-only --workers 1
      if: ${{ matrix.variant.premium }}
      env:
        DEBUG: pw:api
        CODER_E2E_LICENSE: ${{ secrets.CODER_E2E_LICENSE }}
        CODER_E2E_REQUIRE_PREMIUM_TESTS: '1'
      working-directory: site
    - name: Upload Playwright Failed Tests
      if: always() && github.actor != 'dependabot[bot]' && runner.os == 'Linux' &&
        !github.event.pull_request.head.repo.fork
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
      with:
        name: failed-test-videos${{ matrix.variant.premium && '-premium' || '' }}
        path: ./site/test-results/**/*.webm
        retention-days: 7
    - name: Upload debug log
      if: always() && github.actor != 'dependabot[bot]' && runner.os == 'Linux' &&
        !github.event.pull_request.head.repo.fork
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
      with:
        name: coderd-debug-logs${{ matrix.variant.premium && '-premium' || ''  }}
        path: ./site/e2e/test-results/debug.log
        retention-days: 7
    - name: Upload pprof dumps
      if: always() && github.actor != 'dependabot[bot]' && runner.os == 'Linux' &&
        !github.event.pull_request.head.repo.fork
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
      with:
        name: debug-pprof-dumps${{ matrix.variant.premium && '-premium' || ''  }}
        path: ./site/test-results/**/debug-pprof-*.txt
        retention-days: 7
  chromatic:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.site == 'true' || needs.changes.outputs.ci == 'true'
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e
      with:
        egress-policy: audit
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}
        persist-credentials: false
    - name: Setup Node
      uses: ./.github/actions/setup-node
    - name: Publish to Chromatic (non-mainline)
      if: github.ref != 'refs/heads/main' && github.repository_owner == 'coder'
      uses: chromaui/action@07791f8243f4cb2698bf4d00426baf4b2d1cb7e0
      env:
        NODE_OPTIONS: --max_old_space_size=4096
        STORYBOOK: true
      with:
        buildScriptName: storybook:ci
        exitOnceUploaded: true
        exitZeroOnChanges: true
        projectToken: 695c25b6cb65
        workingDir: ./site
        storybookBaseDir: ./site
        storybookConfigDir: ./site/.storybook
        skip: '@(renovate/**|dependabot/**)'
        onlyChanged: true
        zip: true
    - name: Publish to Chromatic (mainline)
      if: github.ref == 'refs/heads/main' && github.repository_owner == 'coder'
      uses: chromaui/action@07791f8243f4cb2698bf4d00426baf4b2d1cb7e0
      env:
        NODE_OPTIONS: --max_old_space_size=4096
        STORYBOOK: true
      with:
        autoAcceptChanges: true
        exitZeroOnChanges: true
        buildScriptName: storybook:build
        projectToken: 695c25b6cb65
        workingDir: ./site
        storybookBaseDir: ./site
        storybookConfigDir: ./site/.storybook
        onlyChanged: true
        zip: true
  offlinedocs:
    name: offlinedocs
    needs: changes
    runs-on: ubuntu-latest
    if: needs.changes.outputs.offlinedocs == 'true' || needs.changes.outputs.ci ==
      'true' || needs.changes.outputs.docs == 'true'
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e
      with:
        egress-policy: audit
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Setup Node
      uses: ./.github/actions/setup-node
      with:
        directory: offlinedocs
    - name: Install Protoc
      run: 'mkdir -p /tmp/proto

        pushd /tmp/proto

        curl -L -o protoc.zip https://github.com/protocolbuffers/protobuf/releases/download/v23.4/protoc-23.4-linux-x86_64.zip

        unzip protoc.zip

        sudo cp -r ./bin/* /usr/local/bin

        sudo cp -r ./include /usr/local/bin/include

        popd

        '
    - name: Setup Go
      uses: ./.github/actions/setup-go
    - name: Install go tools
      uses: ./.github/actions/setup-go-tools
    - name: Setup sqlc
      uses: ./.github/actions/setup-sqlc
    - name: Format
      run: 'cd offlinedocs

        pnpm format:check

        '
    - name: Lint
      run: 'cd offlinedocs

        pnpm lint

        '
    - name: Build
      run: 'make build/coder_docs_"$(./scripts/version.sh)".tgz

        '
  required:
    runs-on: ubuntu-latest
    needs:
    - changes
    - fmt
    - lint
    - lint-actions
    - gen
    - test-go-pg
    - test-go-pg-17
    - test-go-race-pg
    - test-js
    - test-e2e
    - offlinedocs
    - sqlc-vet
    - check-build
    if: always()
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e
      with:
        egress-policy: audit
    - name: Ensure required checks
      run: "echo \"Checking required checks\"\necho \"- changes: ${{ needs.changes.result\
        \ }}\"\necho \"- fmt: ${{ needs.fmt.result }}\"\necho \"- lint: ${{ needs.lint.result\
        \ }}\"\necho \"- lint-actions: ${{ needs.lint-actions.result }}\"\necho \"\
        - gen: ${{ needs.gen.result }}\"\necho \"- test-go-pg: ${{ needs.test-go-pg.result\
        \ }}\"\necho \"- test-go-pg-17: ${{ needs.test-go-pg-17.result }}\"\necho\
        \ \"- test-go-race-pg: ${{ needs.test-go-race-pg.result }}\"\necho \"- test-js:\
        \ ${{ needs.test-js.result }}\"\necho \"- test-e2e: ${{ needs.test-e2e.result\
        \ }}\"\necho \"- offlinedocs: ${{ needs.offlinedocs.result }}\"\necho \"-\
        \ check-build: ${{ needs.check-build.result }}\"\necho\n\n# We allow skipped\
        \ jobs to pass, but not failed or cancelled jobs.\nif [[ \"${{ contains(needs.*.result,\
        \ 'failure') }}\" == \"true\" || \"${{ contains(needs.*.result, 'cancelled')\
        \ }}\" == \"true\" ]]; then\n  echo \"One of the required checks has failed\
        \ or has been cancelled\"\n  exit 1\nfi\n\necho \"Required checks have passed\"\
        \n"
  build-dylib:
    needs: changes
    if: needs.changes.outputs.go == 'true' || needs.changes.outputs.ci == 'true' ||
      github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Setup GNU tools (macOS)
      uses: ./.github/actions/setup-gnu-tools
    - name: Switch XCode Version
      uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd
      with:
        xcode-version: 16.1.0
    - name: Setup Go
      uses: ./.github/actions/setup-go
    - name: Install rcodesign
      if: ${{ github.repository_owner == 'coder' && (github.ref == 'refs/heads/main'
        || startsWith(github.ref, 'refs/heads/release/')) }}
      run: "set -euo pipefail\nwget -O /tmp/rcodesign.tar.gz https://github.com/indygreg/apple-platform-rs/releases/download/apple-codesign%2F0.22.0/apple-codesign-0.22.0-macos-universal.tar.gz\n\
        sudo tar -xzf /tmp/rcodesign.tar.gz \\\n  -C /usr/local/bin \\\n  --strip-components=1\
        \ \\\n  apple-codesign-0.22.0-macos-universal/rcodesign\nrm /tmp/rcodesign.tar.gz\n"
    - name: Setup Apple Developer certificate and API key
      if: ${{ github.repository_owner == 'coder' && (github.ref == 'refs/heads/main'
        || startsWith(github.ref, 'refs/heads/release/')) }}
      run: 'set -euo pipefail

        touch /tmp/{apple_cert.p12,apple_cert_password.txt,apple_apikey.p8}

        chmod 600 /tmp/{apple_cert.p12,apple_cert_password.txt,apple_apikey.p8}

        echo "$AC_CERTIFICATE_P12_BASE64" | base64 -d > /tmp/apple_cert.p12

        echo "$AC_CERTIFICATE_PASSWORD" > /tmp/apple_cert_password.txt

        echo "$AC_APIKEY_P8_BASE64" | base64 -d > /tmp/apple_apikey.p8

        '
      env:
        AC_CERTIFICATE_P12_BASE64: ${{ secrets.AC_CERTIFICATE_P12_BASE64 }}
        AC_CERTIFICATE_PASSWORD: ${{ secrets.AC_CERTIFICATE_PASSWORD }}
        AC_APIKEY_P8_BASE64: ${{ secrets.AC_APIKEY_P8_BASE64 }}
    - name: Build dylibs
      run: 'set -euxo pipefail

        ./.github/scripts/retry.sh -- go mod download


        make gen/mark-fresh

        make build/coder-dylib

        '
      env:
        CODER_SIGN_DARWIN: ${{ (github.ref == 'refs/heads/main' || startsWith(github.ref,
          'refs/heads/release/')) && '1' || '0' }}
        AC_CERTIFICATE_FILE: /tmp/apple_cert.p12
        AC_CERTIFICATE_PASSWORD_FILE: /tmp/apple_cert_password.txt
    - name: Upload build artifacts
      if: ${{ github.repository_owner == 'coder' && (github.ref == 'refs/heads/main'
        || startsWith(github.ref, 'refs/heads/release/')) }}
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
      with:
        name: dylibs
        path: './build/*.h

          ./build/*.dylib

          '
        retention-days: 7
    - name: Delete Apple Developer certificate and API key
      if: ${{ github.repository_owner == 'coder' && (github.ref == 'refs/heads/main'
        || startsWith(github.ref, 'refs/heads/release/')) }}
      run: rm -f /tmp/{apple_cert.p12,apple_cert_password.txt,apple_apikey.p8}
  check-build:
    needs: changes
    if: needs.changes.outputs.go == 'true' && github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e
      with:
        egress-policy: audit
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Setup Node
      uses: ./.github/actions/setup-node
    - name: Setup Go
      uses: ./.github/actions/setup-go
    - name: Install go-winres
      run: ./.github/scripts/retry.sh -- go install github.com/tc-hib/go-winres@d743268d7ea168077ddd443c4240562d4f5e8c3e
    - name: Install nfpm
      run: ./.github/scripts/retry.sh -- go install github.com/goreleaser/nfpm/v2/cmd/nfpm@v2.35.1
    - name: Install zstd
      run: sudo apt-get install -y zstd
    - name: Build
      run: 'set -euxo pipefail

        ./.github/scripts/retry.sh -- go mod download

        make gen/mark-fresh

        make build

        '
  build:
    needs:
    - changes
    - build-dylib
    if: (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/'))
      && needs.changes.outputs.docs-only == 'false' && !github.event.pull_request.head.repo.fork
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write
      attestations: write
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
    outputs:
      IMAGE: ghcr.io/coder/coder-preview:${{ steps.build-docker.outputs.tag }}
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e
      with:
        egress-policy: audit
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: GHCR Login
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup Node
      uses: ./.github/actions/setup-node
    - name: Setup Go
      uses: ./.github/actions/setup-go
    - name: Install rcodesign
      run: "set -euo pipefail\nwget -O /tmp/rcodesign.tar.gz https://github.com/indygreg/apple-platform-rs/releases/download/apple-codesign%2F0.22.0/apple-codesign-0.22.0-x86_64-unknown-linux-musl.tar.gz\n\
        sudo tar -xzf /tmp/rcodesign.tar.gz \\\n  -C /usr/bin \\\n  --strip-components=1\
        \ \\\n  apple-codesign-0.22.0-x86_64-unknown-linux-musl/rcodesign\nrm /tmp/rcodesign.tar.gz\n"
    - name: Setup Apple Developer certificate
      run: 'set -euo pipefail

        touch /tmp/{apple_cert.p12,apple_cert_password.txt}

        chmod 600 /tmp/{apple_cert.p12,apple_cert_password.txt}

        echo "$AC_CERTIFICATE_P12_BASE64" | base64 -d > /tmp/apple_cert.p12

        echo "$AC_CERTIFICATE_PASSWORD" > /tmp/apple_cert_password.txt

        '
      env:
        AC_CERTIFICATE_P12_BASE64: ${{ secrets.AC_CERTIFICATE_P12_BASE64 }}
        AC_CERTIFICATE_PASSWORD: ${{ secrets.AC_CERTIFICATE_PASSWORD }}
    - name: Setup Java
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654
      with:
        distribution: zulu
        java-version: '11.0'
    - name: Install go-winres
      run: ./.github/scripts/retry.sh -- go install github.com/tc-hib/go-winres@d743268d7ea168077ddd443c4240562d4f5e8c3e
    - name: Install nfpm
      run: ./.github/scripts/retry.sh -- go install github.com/goreleaser/nfpm/v2/cmd/nfpm@v2.35.1
    - name: Install zstd
      run: sudo apt-get install -y zstd
    - name: Install cosign
      uses: ./.github/actions/install-cosign
    - name: Install syft
      uses: ./.github/actions/install-syft
    - name: Setup Windows EV Signing Certificate
      run: 'set -euo pipefail

        touch /tmp/ev_cert.pem

        chmod 600 /tmp/ev_cert.pem

        echo "$EV_SIGNING_CERT" > /tmp/ev_cert.pem

        wget https://github.com/ebourg/jsign/releases/download/6.0/jsign-6.0.jar -O
        /tmp/jsign-6.0.jar

        '
      env:
        EV_SIGNING_CERT: ${{ secrets.EV_SIGNING_CERT }}
    - name: Authenticate to Google Cloud
      id: gcloud_auth
      uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093
      with:
        workload_identity_provider: ${{ vars.GCP_CODE_SIGNING_WORKLOAD_ID_PROVIDER
          }}
        service_account: ${{ vars.GCP_CODE_SIGNING_SERVICE_ACCOUNT }}
        token_format: access_token
    - name: Setup GCloud SDK
      uses: google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db
    - name: Download dylibs
      uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131
      with:
        name: dylibs
        path: ./build
    - name: Insert dylibs
      run: 'mv ./build/*amd64.dylib ./site/out/bin/coder-vpn-darwin-amd64.dylib

        mv ./build/*arm64.dylib ./site/out/bin/coder-vpn-darwin-arm64.dylib

        mv ./build/*arm64.h     ./site/out/bin/coder-vpn-darwin-dylib.h

        '
    - name: Build
      run: "set -euxo pipefail\n./.github/scripts/retry.sh -- go mod download\n\n\
        version=\"$(./scripts/version.sh)\"\ntag=\"main-${version//+/-}\"\necho \"\
        tag=$tag\" >> \"$GITHUB_OUTPUT\"\n\nmake gen/mark-fresh\nmake -j \\\n  build/coder_linux_{amd64,arm64,armv7}\
        \ \\\n  build/coder_\"$version\"_windows_amd64.zip \\\n  build/coder_\"$version\"\
        _linux_amd64.{tar.gz,deb}\n"
      env:
        CODER_SIGN_WINDOWS: '1'
        CODER_WINDOWS_RESOURCES: '1'
        CODER_SIGN_GPG: '1'
        CODER_GPG_RELEASE_KEY_BASE64: ${{ secrets.GPG_RELEASE_KEY_BASE64 }}
        CODER_SIGN_DARWIN: '1'
        AC_CERTIFICATE_FILE: /tmp/apple_cert.p12
        AC_CERTIFICATE_PASSWORD_FILE: /tmp/apple_cert_password.txt
        EV_KEY: ${{ secrets.EV_KEY }}
        EV_KEYSTORE: ${{ secrets.EV_KEYSTORE }}
        EV_TSA_URL: ${{ secrets.EV_TSA_URL }}
        EV_CERTIFICATE_PATH: /tmp/ev_cert.pem
        GCLOUD_ACCESS_TOKEN: ${{ steps.gcloud_auth.outputs.access_token }}
        JSIGN_PATH: /tmp/jsign-6.0.jar
    - name: Build Linux Docker images
      id: build-docker
      env:
        CODER_IMAGE_BASE: ghcr.io/coder/coder-preview
        DOCKER_CLI_EXPERIMENTAL: enabled
      run: "set -euxo pipefail\n\n# build Docker images for each architecture\nversion=\"\
        $(./scripts/version.sh)\"\ntag=\"${version//+/-}\"\necho \"tag=$tag\" >> \"\
        $GITHUB_OUTPUT\"\n\n# build images for each architecture\n# note: omitting\
        \ the -j argument to avoid race conditions when pushing\nmake build/coder_\"\
        $version\"_linux_{amd64,arm64,armv7}.tag\n\n# only push if we are on main\
        \ branch or release branch\nif [[ \"${GITHUB_REF}\" == \"refs/heads/main\"\
        \ || \"${GITHUB_REF}\" == refs/heads/release/* ]]; then\n  # build and push\
        \ multi-arch manifest, this depends on the other images\n  # being pushed\
        \ so will automatically push them\n  # note: omitting the -j argument to avoid\
        \ race conditions when pushing\n  make push/build/coder_\"$version\"_linux_{amd64,arm64,armv7}.tag\n\
        \n  # Define specific tags\n  tags=(\"$tag\")\n  if [ \"${GITHUB_REF}\" ==\
        \ \"refs/heads/main\" ]; then\n    tags+=(\"main\" \"latest\")\n  elif [[\
        \ \"${GITHUB_REF}\" == refs/heads/release/* ]]; then\n    tags+=(\"release-${GITHUB_REF#refs/heads/release/}\"\
        )\n  fi\n\n  # Create and push a multi-arch manifest for each tag\n  # we\
        \ are adding `latest` tag and keeping `main` for backward\n  # compatibality\n\
        \  for t in \"${tags[@]}\"; do\n    echo \"Pushing multi-arch manifest for\
        \ tag: $t\"\n    # shellcheck disable=SC2046\n    ./scripts/build_docker_multiarch.sh\
        \ \\\n        --push \\\n        --target \"ghcr.io/coder/coder-preview:$t\"\
        \ \\\n        --version \"$version\" \\\n        $(cat build/coder_\"$version\"\
        _linux_{amd64,arm64,armv7}.tag)\n  done\nfi\n"
    - name: SBOM Generation and Attestation
      if: github.ref == 'refs/heads/main'
      continue-on-error: true
      env:
        COSIGN_EXPERIMENTAL: 1
        BUILD_TAG: ${{ steps.build-docker.outputs.tag }}
      run: "set -euxo pipefail\n\n# Define image base and tags\nIMAGE_BASE=\"ghcr.io/coder/coder-preview\"\
        \nTAGS=(\"${BUILD_TAG}\" \"main\" \"latest\")\n\n# Generate and attest SBOM\
        \ for each tag\nfor tag in \"${TAGS[@]}\"; do\n  IMAGE=\"${IMAGE_BASE}:${tag}\"\
        \n  SBOM_FILE=\"coder_sbom_${tag//[:\\/]/_}.spdx.json\"\n\n  echo \"Generating\
        \ SBOM for image: ${IMAGE}\"\n  syft \"${IMAGE}\" -o spdx-json > \"${SBOM_FILE}\"\
        \n\n  echo \"Attesting SBOM to image: ${IMAGE}\"\n  cosign clean --force=true\
        \ \"${IMAGE}\"\n  cosign attest --type spdxjson \\\n    --predicate \"${SBOM_FILE}\"\
        \ \\\n    --yes \\\n    \"${IMAGE}\"\ndone\n"
    - name: GitHub Attestation for Docker image
      id: attest_main
      if: github.ref == 'refs/heads/main'
      continue-on-error: true
      uses: actions/attest@e59cbc1ad1ac2d59339667419eb8cdde6eb61e3d
      with:
        subject-name: ghcr.io/coder/coder-preview:main
        predicate-type: https://slsa.dev/provenance/v1
        predicate: "{\n  \"buildType\": \"https://github.com/actions/runner-images/\"\
          ,\n  \"builder\": {\n    \"id\": \"https://github.com/${{ github.repository\
          \ }}/actions/runs/${{ github.run_id }}\"\n  },\n  \"invocation\": {\n  \
          \  \"configSource\": {\n      \"uri\": \"git+https://github.com/${{ github.repository\
          \ }}@${{ github.ref }}\",\n      \"digest\": {\n        \"sha1\": \"${{\
          \ github.sha }}\"\n      },\n      \"entryPoint\": \".github/workflows/ci.yaml\"\
          \n    },\n    \"environment\": {\n      \"github_workflow\": \"${{ github.workflow\
          \ }}\",\n      \"github_run_id\": \"${{ github.run_id }}\"\n    }\n  },\n\
          \  \"metadata\": {\n    \"buildInvocationID\": \"${{ github.run_id }}\"\
          ,\n    \"completeness\": {\n      \"environment\": true,\n      \"materials\"\
          : true\n    }\n  }\n}\n"
        push-to-registry: true
    - name: GitHub Attestation for Docker image (latest tag)
      id: attest_latest
      if: github.ref == 'refs/heads/main'
      continue-on-error: true
      uses: actions/attest@e59cbc1ad1ac2d59339667419eb8cdde6eb61e3d
      with:
        subject-name: ghcr.io/coder/coder-preview:latest
        predicate-type: https://slsa.dev/provenance/v1
        predicate: "{\n  \"buildType\": \"https://github.com/actions/runner-images/\"\
          ,\n  \"builder\": {\n    \"id\": \"https://github.com/${{ github.repository\
          \ }}/actions/runs/${{ github.run_id }}\"\n  },\n  \"invocation\": {\n  \
          \  \"configSource\": {\n      \"uri\": \"git+https://github.com/${{ github.repository\
          \ }}@${{ github.ref }}\",\n      \"digest\": {\n        \"sha1\": \"${{\
          \ github.sha }}\"\n      },\n      \"entryPoint\": \".github/workflows/ci.yaml\"\
          \n    },\n    \"environment\": {\n      \"github_workflow\": \"${{ github.workflow\
          \ }}\",\n      \"github_run_id\": \"${{ github.run_id }}\"\n    }\n  },\n\
          \  \"metadata\": {\n    \"buildInvocationID\": \"${{ github.run_id }}\"\
          ,\n    \"completeness\": {\n      \"environment\": true,\n      \"materials\"\
          : true\n    }\n  }\n}\n"
        push-to-registry: true
    - name: GitHub Attestation for version-specific Docker image
      id: attest_version
      if: github.ref == 'refs/heads/main'
      continue-on-error: true
      uses: actions/attest@e59cbc1ad1ac2d59339667419eb8cdde6eb61e3d
      with:
        subject-name: ghcr.io/coder/coder-preview:${{ steps.build-docker.outputs.tag
          }}
        predicate-type: https://slsa.dev/provenance/v1
        predicate: "{\n  \"buildType\": \"https://github.com/actions/runner-images/\"\
          ,\n  \"builder\": {\n    \"id\": \"https://github.com/${{ github.repository\
          \ }}/actions/runs/${{ github.run_id }}\"\n  },\n  \"invocation\": {\n  \
          \  \"configSource\": {\n      \"uri\": \"git+https://github.com/${{ github.repository\
          \ }}@${{ github.ref }}\",\n      \"digest\": {\n        \"sha1\": \"${{\
          \ github.sha }}\"\n      },\n      \"entryPoint\": \".github/workflows/ci.yaml\"\
          \n    },\n    \"environment\": {\n      \"github_workflow\": \"${{ github.workflow\
          \ }}\",\n      \"github_run_id\": \"${{ github.run_id }}\"\n    }\n  },\n\
          \  \"metadata\": {\n    \"buildInvocationID\": \"${{ github.run_id }}\"\
          ,\n    \"completeness\": {\n      \"environment\": true,\n      \"materials\"\
          : true\n    }\n  }\n}\n"
        push-to-registry: true
    - name: Check attestation status
      if: github.ref == 'refs/heads/main'
      run: "if [[ \"${{ steps.attest_main.outcome }}\" == \"failure\" ]]; then\n \
        \ echo \"::warning::GitHub attestation for main tag failed\"\nfi\nif [[ \"\
        ${{ steps.attest_latest.outcome }}\" == \"failure\" ]]; then\n  echo \"::warning::GitHub\
        \ attestation for latest tag failed\"\nfi\nif [[ \"${{ steps.attest_version.outcome\
        \ }}\" == \"failure\" ]]; then\n  echo \"::warning::GitHub attestation for\
        \ version-specific tag failed\"\nfi\n"
    - name: Prune old images
      if: github.ref == 'refs/heads/main'
      uses: vlaurin/action-ghcr-prune@0cf7d39f88546edd31965acba78cdcb0be14d641
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        organization: coder
        container: coder-preview
        keep-younger-than: 7
        keep-tags: latest
        keep-tags-regexes: ^pr
        prune-tags-regexes: '^main-

          ^v

          '
        prune-untagged: true
    - name: Upload build artifacts
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
      with:
        name: coder
        path: './build/*.zip

          ./build/*.tar.gz

          ./build/*.deb

          '
        retention-days: 7
  deploy:
    needs:
    - changes
    - build
    if: '(github.ref == ''refs/heads/main'' || startsWith(github.ref, ''refs/heads/release/''))

      && needs.changes.outputs.docs-only == ''false''

      && !github.event.pull_request.head.repo.fork

      '
    uses: ./.github/workflows/deploy.yaml
    with:
      image: ${{ needs.build.outputs.IMAGE }}
    permissions:
      contents: read
      id-token: write
      packages: write
    secrets:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      FLY_PARIS_CODER_PROXY_SESSION_TOKEN: ${{ secrets.FLY_PARIS_CODER_PROXY_SESSION_TOKEN
        }}
      FLY_SYDNEY_CODER_PROXY_SESSION_TOKEN: ${{ secrets.FLY_SYDNEY_CODER_PROXY_SESSION_TOKEN
        }}
      FLY_SAO_PAULO_CODER_PROXY_SESSION_TOKEN: ${{ secrets.FLY_SAO_PAULO_CODER_PROXY_SESSION_TOKEN
        }}
      FLY_JNB_CODER_PROXY_SESSION_TOKEN: ${{ secrets.FLY_JNB_CODER_PROXY_SESSION_TOKEN
        }}
  sqlc-vet:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.db == 'true' || needs.changes.outputs.ci == 'true' ||
      github.ref == 'refs/heads/main'
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e
      with:
        egress-policy: audit
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        fetch-depth: 1
        persist-credentials: false
    - name: Setup Go
      uses: ./.github/actions/setup-go
    - name: Setup sqlc
      uses: ./.github/actions/setup-sqlc
    - name: Setup and run sqlc vet
      run: 'make sqlc-vet

        '
  notify-slack-on-failure:
    needs:
    - required
    runs-on: ubuntu-latest
    if: failure() && github.ref == 'refs/heads/main'
    steps:
    - name: Send Slack notification
      run: "ESCAPED_PROMPT=$(printf \"%s\" \"<@U09LQ75AHKR> $BLINK_CI_FAILURE_PROMPT\"\
        \ | jq -Rsa .)\ncurl -X POST -H 'Content-type: application/json' \\\n--data\
        \ '{\n  \"blocks\": [\n    {\n      \"type\": \"header\",\n      \"text\"\
        : {\n        \"type\": \"plain_text\",\n        \"text\": \"\u274C CI Failure\
        \ in main\",\n        \"emoji\": true\n      }\n    },\n    {\n      \"type\"\
        : \"section\",\n      \"text\": {\n        \"type\": \"mrkdwn\",\n       \
        \ \"text\": \"*View failure:* <'\"${RUN_URL}\"'|Click here>\"\n      }\n \
        \   },\n    {\n      \"type\": \"section\",\n      \"text\": {\n        \"\
        type\": \"mrkdwn\",\n        \"text\": '\"$ESCAPED_PROMPT\"'\n      }\n  \
        \  }\n  ]\n}' \"${SLACK_WEBHOOK}\"\n"
      env:
        SLACK_WEBHOOK: ${{ secrets.CI_FAILURE_SLACK_WEBHOOK }}
        RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{
          github.run_id }}
        BLINK_CI_FAILURE_PROMPT: ${{ vars.BLINK_CI_FAILURE_PROMPT }}
