name: contrib
on:
  workflow_dispatch: {}
permissions:
  contents: read
concurrency: pr-${{ github.ref }}
jobs:
  cla:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - name: cla
      if: (github.event.comment.body == 'recheck' || github.event.comment.body ==
        'I have read the CLA Document and I hereby sign the CLA') || github.event_name
        == 'pull_request_target'
      uses: contributor-assistant/github-action@ca4a40a7d1004f18d9960b404b97e5f30a505a08
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PERSONAL_ACCESS_TOKEN: ${{ secrets.CDRCI2_GITHUB_TOKEN }}
      with:
        remote-organization-name: coder
        remote-repository-name: cla
        path-to-signatures: v2022-09-04/signatures.json
        path-to-document: https://github.com/coder/cla/blob/main/README.md
        branch: main
        allowlist: coryb,aaronlehmann,dependabot*,blink-so*,blinkagent*
  release-labels:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: ${{ github.event_name == 'pull_request_target' && !github.event.pull_request.draft
      }}
    steps:
    - name: release-labels
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd
      with:
        script: "const releaseLabels = {\n  breaking: \"release/breaking\",\n}\n\n\
          const { action, changes, label, pull_request } = context.payload\nconst\
          \ { title } = pull_request\nconst labels = pull_request.labels.map((label)\
          \ => label.name)\nconst isBreakingTitle = isBreaking(title)\n\n// Debug\
          \ information.\nconsole.log(\"Action: %s\", action)\nconsole.log(\"Title:\
          \ %s\", title)\nconsole.log(\"Labels: %s\", labels.join(\", \"))\n\nconst\
          \ params = {\n  issue_number: context.issue.number,\n  owner: context.repo.owner,\n\
          \  repo: context.repo.repo,\n}\n\nif (action === \"opened\" || action ===\
          \ \"reopened\" || action === \"ready_for_review\") {\n  if (isBreakingTitle\
          \ && !labels.includes(releaseLabels.breaking)) {\n    console.log('Add \"\
          %s\" label', releaseLabels.breaking)\n    await github.rest.issues.addLabels({\n\
          \      ...params,\n      labels: [releaseLabels.breaking],\n    })\n  }\n\
          }\n\nif (action === \"edited\" && changes.title) {\n  if (isBreakingTitle\
          \ && !labels.includes(releaseLabels.breaking)) {\n    console.log('Add \"\
          %s\" label', releaseLabels.breaking)\n    await github.rest.issues.addLabels({\n\
          \      ...params,\n      labels: [releaseLabels.breaking],\n    })\n  }\n\
          \n  if (!isBreakingTitle && labels.includes(releaseLabels.breaking)) {\n\
          \    const wasBreakingTitle = isBreaking(changes.title.from)\n    if (wasBreakingTitle)\
          \ {\n      console.log('Remove \"%s\" label', releaseLabels.breaking)\n\
          \      await github.rest.issues.removeLabel({\n        ...params,\n    \
          \    name: releaseLabels.breaking,\n      })\n    } else {\n      console.log('Rename\
          \ title from \"%s\" to \"%s\"', title, toBreaking(title))\n      await github.rest.issues.update({\n\
          \        ...params,\n        title: toBreaking(title),\n      })\n    }\n\
          \  }\n}\n\nif (action === \"labeled\") {\n  if (label.name === releaseLabels.breaking\
          \ && !isBreakingTitle) {\n    console.log('Rename title from \"%s\" to \"\
          %s\"', title, toBreaking(title))\n    await github.rest.issues.update({\n\
          \      ...params,\n      title: toBreaking(title),\n    })\n  }\n}\n\nif\
          \ (action === \"unlabeled\") {\n  if (label.name === releaseLabels.breaking\
          \ && isBreakingTitle) {\n    console.log('Rename title from \"%s\" to \"\
          %s\"', title, fromBreaking(title))\n    await github.rest.issues.update({\n\
          \      ...params,\n      title: fromBreaking(title),\n    })\n  }\n}\n\n\
          function isBreaking(t) {\n  return t.split(\" \")[0].endsWith(\"!:\")\n\
          }\n\nfunction toBreaking(t) {\n  const parts = t.split(\" \")\n  return\
          \ [parts[0].replace(/:$/, \"!:\"), ...parts.slice(1)].join(\" \")\n}\n\n\
          function fromBreaking(t) {\n  const parts = t.split(\" \")\n  return [parts[0].replace(/!:$/,\
          \ \":\"), ...parts.slice(1)].join(\" \")\n}\n"
