name: dependabot
on:
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  dependabot-automerge:
    runs-on: ubuntu-latest
    if: 'github.event_name == ''pull_request'' && github.event.action == ''opened''
      && github.event.pull_request.user.login == ''dependabot[bot]'' && github.event.pull_request.user.id
      == 49699333 && github.repository == ''coder/coder''

      '
    permissions:
      pull-requests: write
      contents: write
    steps:
    - name: Dependabot metadata
      id: metadata
      uses: dependabot/fetch-metadata@21025c705c08248db411dc16f3619e6b5f9ea21a
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Approve the PR
      if: steps.metadata.outputs.package-ecosystem != 'github-actions'
      run: 'echo "Approving $PR_URL"

        gh pr review --approve "$PR_URL"

        '
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Enable auto-merge
      if: steps.metadata.outputs.package-ecosystem != 'github-actions'
      run: 'echo "Enabling auto-merge for $PR_URL"

        gh pr merge --auto --squash "$PR_URL"

        '
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Send Slack notification
      run: "if [ \"$PACKAGE_ECOSYSTEM\" = \"github-actions\" ]; then\n  STATUS_TEXT=\"\
        :pr-opened: Dependabot opened PR #${PR_NUMBER} (GitHub Actions changes are\
        \ not auto-merged)\"\nelse\n  STATUS_TEXT=\":pr-merged: Auto merge enabled\
        \ for Dependabot PR #${PR_NUMBER}\"\nfi\ncurl -X POST -H 'Content-type: application/json'\
        \ \\\n--data '{\n  \"username\": \"dependabot\",\n  \"icon_url\": \"https://avatars.githubusercontent.com/u/27347476\"\
        ,\n  \"blocks\": [\n    {\n      \"type\": \"header\",\n      \"text\": {\n\
        \        \"type\": \"plain_text\",\n        \"text\": \"'\"${STATUS_TEXT}\"\
        '\",\n        \"emoji\": true\n      }\n    },\n    {\n      \"type\": \"\
        section\",\n      \"fields\": [\n        {\n          \"type\": \"mrkdwn\"\
        ,\n          \"text\": \"'\"${PR_TITLE}\"'\"\n        }\n      ]\n    },\n\
        \    {\n      \"type\": \"actions\",\n      \"elements\": [\n        {\n \
        \         \"type\": \"button\",\n          \"text\": {\n            \"type\"\
        : \"plain_text\",\n            \"text\": \"View PR\"\n          },\n     \
        \     \"url\": \"'\"${PR_URL}\"'\"\n        }\n      ]\n    }\n  ]\n}' \"\
        ${{ secrets.DEPENDABOT_PRS_SLACK_WEBHOOK }}\"\n"
      env:
        SLACK_WEBHOOK: ${{ secrets.DEPENDABOT_PRS_SLACK_WEBHOOK }}
        PACKAGE_ECOSYSTEM: ${{ steps.metadata.outputs.package-ecosystem }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        PR_TITLE: ${{ github.event.pull_request.title }}
        PR_URL: ${{ github.event.pull_request.html_url }}
