name: docker-base
on:
  workflow_dispatch: {}
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-docker-base
jobs:
  build:
    permissions:
      id-token: write
      packages: write
    runs-on: ubuntu-latest
    if: github.repository_owner == 'coder'
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e
      with:
        egress-policy: audit
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        persist-credentials: false
    - name: Docker login
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Create empty base-build-context directory
      run: mkdir base-build-context
    - name: Install depot.dev CLI
      uses: depot/setup-action@15c09a5f77a0840ad4bce955686522a257853461
    - name: Build base Docker image via depot.dev
      uses: depot/build-push-action@5f3b3c2e5a00f0093de47f657aeaefcedff27d18
      with:
        project: wl5hnrrkns
        context: base-build-context
        file: scripts/Dockerfile.base
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        provenance: true
        pull: true
        no-cache: true
        push: ${{ github.event_name != 'pull_request' }}
        tags: 'ghcr.io/coder/coder-base:latest

          '
    - name: Verify that images are pushed properly
      if: github.event_name != 'pull_request'
      run: "# retry 10 times with a 5 second delay as the images may not be\n# available\
        \ immediately\nfor i in {1..10}; do\n  rc=0\n  raw_manifests=$(docker buildx\
        \ imagetools inspect --raw ghcr.io/coder/coder-base:latest) || rc=$?\n  if\
        \ [[ \"$rc\" -eq 0 ]]; then\n    break\n  fi\n  if [[ \"$i\" -eq 10 ]]; then\n\
        \    echo \"Failed to pull manifests after 10 retries\"\n    exit 1\n  fi\n\
        \  echo \"Failed to pull manifests, retrying in 5 seconds\"\n  sleep 5\ndone\n\
        \nmanifests=$(\n  echo \"$raw_manifests\" | \\\n    jq -r '.manifests[].platform\
        \ | .os + \"/\" + .architecture + (if .variant then \"/\" + .variant else\
        \ \"\" end)'\n)\n\n# Verify all 3 platforms are present.\nset -euxo pipefail\n\
        echo \"$manifests\" | grep -q linux/amd64\necho \"$manifests\" | grep -q linux/arm64\n\
        echo \"$manifests\" | grep -q linux/arm/v7\n"
