name: dogfood
on:
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  build_image:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e
      with:
        egress-policy: audit
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        persist-credentials: false
    - name: Setup Nix
      uses: nixbuild/nix-quick-install-action@2c9db80fb984ceb1bcaa77cdda3fdf8cfba92035
      with:
        nix_version: 2.28.5
    - uses: nix-community/cache-nix-action@7df957e333c1e5da7721f60227dbba6d06080569
      with:
        primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock')
          }}
        restore-prefixes-first-match: nix-${{ runner.os }}-
        gc-max-store-size-linux: 5G
        purge: true
        purge-prefixes: nix-${{ runner.os }}-
        purge-created: 0
        purge-primary-key: never
    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@5250492686b253f06fa55861556d1027b067aeb5
    - name: Branch name to Docker tag name
      id: docker-tag-name
      run: '# Replace / with --, e.g. user/feature => user--feature.

        tag=${BRANCH_NAME//\//--}

        echo "tag=${tag}" >> "$GITHUB_OUTPUT"

        '
      env:
        BRANCH_NAME: ${{ steps.branch-name.outputs.current_branch }}
    - name: Set up Depot CLI
      uses: depot/setup-action@15c09a5f77a0840ad4bce955686522a257853461
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f
    - name: Login to DockerHub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push Non-Nix image
      uses: depot/build-push-action@5f3b3c2e5a00f0093de47f657aeaefcedff27d18
      with:
        project: b4q6ltmpzh
        token: ${{ secrets.DEPOT_TOKEN }}
        buildx-fallback: true
        context: '{{defaultContext}}:dogfood/coder'
        pull: true
        save: true
        push: ${{ github.ref == 'refs/heads/main' }}
        tags: codercom/oss-dogfood:${{ steps.docker-tag-name.outputs.tag }},codercom/oss-dogfood:latest
    - name: Build Nix image
      run: nix build .#dev_image
    - name: Push Nix image
      if: github.ref == 'refs/heads/main'
      run: 'docker load -i result


        CURRENT_SYSTEM=$(nix eval --impure --raw --expr ''builtins.currentSystem'')


        docker image tag "codercom/oss-dogfood-nix:latest-$CURRENT_SYSTEM" "codercom/oss-dogfood-nix:${DOCKER_TAG}"

        docker image push "codercom/oss-dogfood-nix:${DOCKER_TAG}"


        docker image tag "codercom/oss-dogfood-nix:latest-$CURRENT_SYSTEM" "codercom/oss-dogfood-nix:latest"

        docker image push "codercom/oss-dogfood-nix:latest"

        '
      env:
        DOCKER_TAG: ${{ steps.docker-tag-name.outputs.tag }}
  deploy_template:
    needs: build_image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e
      with:
        egress-policy: audit
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        persist-credentials: false
    - name: Setup Terraform
      uses: ./.github/actions/setup-tf
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093
      with:
        workload_identity_provider: ${{ vars.GCP_WORKLOAD_ID_PROVIDER }}
        service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}
    - name: Terraform init and validate
      run: 'pushd dogfood/

        terraform init

        terraform validate

        popd

        pushd dogfood/coder

        terraform init

        terraform validate

        popd

        pushd dogfood/coder-envbuilder

        terraform init

        terraform validate

        popd

        '
    - name: Get short commit SHA
      if: github.ref == 'refs/heads/main'
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
    - name: Get latest commit title
      if: github.ref == 'refs/heads/main'
      id: message
      run: echo "pr_title=$(git log --format=%s -n 1 ${{ github.sha }})" >> "$GITHUB_OUTPUT"
    - name: Push template
      if: github.ref == 'refs/heads/main'
      run: 'cd dogfood

        terraform apply -auto-approve

        '
      env:
        CODER_URL: https://dev.coder.com
        CODER_SESSION_TOKEN: ${{ secrets.CODER_SESSION_TOKEN }}
        TF_VAR_CODER_DOGFOOD_ANTHROPIC_API_KEY: ${{ secrets.CODER_DOGFOOD_ANTHROPIC_API_KEY
          }}
        TF_VAR_CODER_TEMPLATE_NAME: ${{ secrets.CODER_TEMPLATE_NAME }}
        TF_VAR_CODER_TEMPLATE_VERSION: ${{ steps.vars.outputs.sha_short }}
        TF_VAR_CODER_TEMPLATE_DIR: ./coder
        TF_VAR_CODER_TEMPLATE_MESSAGE: ${{ steps.message.outputs.pr_title }}
        TF_LOG: info
