name: nightly-gauntlet
on:
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  test-go-pg:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    strategy:
      fail-fast: false
      matrix:
        os:
        - macos-latest
        - windows-2022
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e
      with:
        egress-policy: audit
    - name: Disable Spotlight Indexing
      if: runner.os == 'macOS'
      run: "enabled=$(sudo mdutil -a -s | { grep -Fc \"Indexing enabled\" || true;\
        \ })\nif [ \"$enabled\" -eq 0 ]; then\n  echo \"Spotlight indexing is already\
        \ disabled\"\n  exit 0\nfi\nsudo mdutil -a -i off\nsudo mdutil -X /\nsudo\
        \ launchctl bootout system /System/Library/LaunchDaemons/com.apple.metadata.mds.plist\n"
    - name: Setup RAM Disks
      if: runner.os == 'Windows'
      uses: coder/setup-ramdisk-action@e1100847ab2d7bcd9d14bcda8f2d1b0f07b36f1b
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        fetch-depth: 1
        persist-credentials: false
    - name: Setup GNU tools (macOS)
      uses: ./.github/actions/setup-gnu-tools
    - name: Setup Go
      uses: ./.github/actions/setup-go
      with:
        use-preinstalled-go: ${{ runner.os == 'Windows' }}
    - name: Setup Terraform
      uses: ./.github/actions/setup-tf
    - name: Setup Embedded Postgres Cache Paths
      id: embedded-pg-cache
      uses: ./.github/actions/setup-embedded-pg-cache-paths
    - name: Download Embedded Postgres Cache
      id: download-embedded-pg-cache
      uses: ./.github/actions/embedded-pg-cache/download
      with:
        key-prefix: embedded-pg-${{ runner.os }}-${{ runner.arch }}
        cache-path: ${{ steps.embedded-pg-cache.outputs.cached-dirs }}
    - name: Setup RAM disk for Embedded Postgres (Windows)
      if: runner.os == 'Windows'
      shell: bash
      run: mkdir -p "R:/temp/embedded-pg"
    - name: Setup RAM disk for Embedded Postgres (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: 'mkdir -p /tmp/tmpfs

        sudo mount_tmpfs -o noowners -s 8g /tmp/tmpfs

        '
    - name: Test with PostgreSQL Database (macOS)
      if: runner.os == 'macOS'
      uses: ./.github/actions/test-go-pg
      with:
        postgres-version: '13'
        test-parallelism-packages: '8'
        test-parallelism-tests: '16'
        test-count: '1'
        embedded-pg-path: /tmp/tmpfs/embedded-pg
        embedded-pg-cache: ${{ steps.embedded-pg-cache.outputs.embedded-pg-cache }}
    - name: Test with PostgreSQL Database (Windows)
      if: runner.os == 'Windows'
      uses: ./.github/actions/test-go-pg
      with:
        postgres-version: '13'
        test-parallelism-packages: '8'
        test-parallelism-tests: '16'
        test-count: '1'
        embedded-pg-path: R:/temp/embedded-pg
        embedded-pg-cache: ${{ steps.embedded-pg-cache.outputs.embedded-pg-cache }}
    - name: Upload Embedded Postgres Cache
      uses: ./.github/actions/embedded-pg-cache/upload
      with:
        cache-key: ${{ steps.download-embedded-pg-cache.outputs.cache-key }}
        cache-path: ${{ steps.embedded-pg-cache.outputs.embedded-pg-cache }}
    - name: Upload test stats to Datadog
      timeout-minutes: 1
      continue-on-error: true
      uses: ./.github/actions/upload-datadog
      if: success() || failure()
      with:
        api-key: ${{ secrets.DATADOG_API_KEY }}
  notify-slack-on-failure:
    needs:
    - test-go-pg
    runs-on: ubuntu-latest
    if: failure()
    steps:
    - name: Send Slack notification
      run: "ESCAPED_PROMPT=$(printf \"%s\" \"<@U09LQ75AHKR> $BLINK_CI_FAILURE_PROMPT\"\
        \ | jq -Rsa .)\ncurl -X POST -H 'Content-type: application/json' \\\n--data\
        \ '{\n  \"blocks\": [\n    {\n      \"type\": \"header\",\n      \"text\"\
        : {\n        \"type\": \"plain_text\",\n        \"text\": \"\u274C Nightly\
        \ gauntlet failed\",\n        \"emoji\": true\n      }\n    },\n    {\n  \
        \    \"type\": \"section\",\n      \"text\": {\n        \"type\": \"mrkdwn\"\
        ,\n        \"text\": \"*View failure:* <'\"${RUN_URL}\"'|Click here>\"\n \
        \     }\n    },\n    {\n      \"type\": \"section\",\n      \"text\": {\n\
        \        \"type\": \"mrkdwn\",\n        \"text\": '\"$ESCAPED_PROMPT\"'\n\
        \      }\n    }\n  ]\n}' \"${SLACK_WEBHOOK}\"\n"
      env:
        SLACK_WEBHOOK: ${{ secrets.CI_FAILURE_SLACK_WEBHOOK }}
        RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{
          github.run_id }}
        BLINK_CI_FAILURE_PROMPT: ${{ vars.BLINK_CI_FAILURE_PROMPT }}
