name: pr-cleanup
on:
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e
      with:
        egress-policy: audit
    - name: Get PR number
      id: pr_number
      run: "if [ -n \"${{ github.event.pull_request.number }}\" ]; then\n  echo \"\
        PR_NUMBER=${{ github.event.pull_request.number }}\" >> \"$GITHUB_OUTPUT\"\n\
        else\n  echo \"PR_NUMBER=${PR_NUMBER}\" >> \"$GITHUB_OUTPUT\"\nfi\n"
      env:
        PR_NUMBER: ${{ github.event.inputs.pr_number }}
    - name: Delete image
      continue-on-error: true
      uses: bots-house/ghcr-delete-image-action@3827559c68cb4dcdf54d813ea9853be6d468d3a4
      with:
        owner: coder
        name: coder-preview
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: pr${{ steps.pr_number.outputs.PR_NUMBER }}
    - name: Set up kubeconfig
      run: 'set -euo pipefail

        mkdir -p ~/.kube

        echo "${{ secrets.PR_DEPLOYMENTS_KUBECONFIG }}" > ~/.kube/config

        export KUBECONFIG=~/.kube/config

        '
    - name: Delete helm release
      run: 'set -euo pipefail

        helm delete --namespace "pr${PR_NUMBER}" "pr${PR_NUMBER}" || echo "helm release
        not found"

        '
      env:
        PR_NUMBER: ${{ steps.pr_number.outputs.PR_NUMBER }}
    - name: Remove PR namespace
      run: 'kubectl delete namespace "pr${PR_NUMBER}" || echo "namespace not found"

        '
      env:
        PR_NUMBER: ${{ steps.pr_number.outputs.PR_NUMBER }}
    - name: Remove DNS records
      run: "set -euo pipefail\n# Get identifier for the record\nrecord_id=$(curl -X\
        \ GET \"https://api.cloudflare.com/client/v4/zones/${{ secrets.PR_DEPLOYMENTS_ZONE_ID\
        \ }}/dns_records?name=%2A.pr${PR_NUMBER}.${{ secrets.PR_DEPLOYMENTS_DOMAIN\
        \ }}\" \\\n-H \"Authorization: Bearer ${{ secrets.PR_DEPLOYMENTS_CLOUDFLARE_API_TOKEN\
        \ }}\" \\\n-H \"Content-Type:application/json\" | jq -r '.result[0].id') ||\
        \ echo \"DNS record not found\"\n\necho \"::add-mask::$record_id\"\n\n# Delete\
        \ the record\n(\n  curl -X DELETE \"https://api.cloudflare.com/client/v4/zones/${{\
        \ secrets.PR_DEPLOYMENTS_ZONE_ID }}/dns_records/$record_id\" \\\n  -H \"Authorization:\
        \ Bearer ${{ secrets.PR_DEPLOYMENTS_CLOUDFLARE_API_TOKEN }}\" \\\n  -H \"\
        Content-Type:application/json\" | jq -r '.success'\n) || echo \"DNS record\
        \ not found\"\n"
      env:
        PR_NUMBER: ${{ steps.pr_number.outputs.PR_NUMBER }}
    - name: Delete certificate
      if: ${{ github.event.pull_request.merged == true }}
      run: 'set -euxo pipefail

        kubectl delete certificate "pr${PR_NUMBER}-tls" -n pr-deployment-certs ||
        echo "certificate not found"

        '
      env:
        PR_NUMBER: ${{ steps.pr_number.outputs.PR_NUMBER }}
