name: Deploy PR
on:
  workflow_dispatch: {}
env:
  REPO: ghcr.io/coder/coder-preview
permissions:
  contents: read
jobs:
  check_pr:
    runs-on: ubuntu-latest
    outputs:
      PR_OPEN: ${{ steps.check_pr.outputs.pr_open }}
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e
      with:
        egress-policy: audit
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        persist-credentials: false
    - name: Check if PR is open
      id: check_pr
      run: "set -euo pipefail\npr_open=true\nif [[ \"$(gh pr view --json state | jq\
        \ -r '.state')\" != \"OPEN\" ]]; then\n  echo \"PR doesn't exist or is closed.\"\
        \n  pr_open=false\nfi\necho \"pr_open=$pr_open\" >> \"$GITHUB_OUTPUT\"\n"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  get_info:
    needs: check_pr
    if: ${{ needs.check_pr.outputs.PR_OPEN == 'true' }}
    outputs:
      PR_NUMBER: ${{ steps.pr_info.outputs.PR_NUMBER }}
      PR_TITLE: ${{ steps.pr_info.outputs.PR_TITLE }}
      PR_URL: ${{ steps.pr_info.outputs.PR_URL }}
      CODER_BASE_IMAGE_TAG: ${{ steps.set_tags.outputs.CODER_BASE_IMAGE_TAG }}
      CODER_IMAGE_TAG: ${{ steps.set_tags.outputs.CODER_IMAGE_TAG }}
      NEW: ${{ steps.check_deployment.outputs.NEW }}
      BUILD: ${{ steps.build_conditionals.outputs.first_or_force_build == 'true' ||
        steps.build_conditionals.outputs.automatic_rebuild == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e
      with:
        egress-policy: audit
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Get PR number, title, and branch name
      id: pr_info
      run: "set -euo pipefail\nPR_NUMBER=$(gh pr view --json number | jq -r '.number')\n\
        PR_TITLE=$(gh pr view --json title | jq -r '.title')\nPR_URL=$(gh pr view\
        \ --json url | jq -r '.url')\n{\n  echo \"PR_URL=$PR_URL\"\n  echo \"PR_NUMBER=$PR_NUMBER\"\
        \n  echo \"PR_TITLE=$PR_TITLE\"\n} >> \"$GITHUB_OUTPUT\"\n"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Set required tags
      id: set_tags
      run: 'set -euo pipefail

        echo "CODER_BASE_IMAGE_TAG=$CODER_BASE_IMAGE_TAG" >> "$GITHUB_OUTPUT"

        echo "CODER_IMAGE_TAG=$CODER_IMAGE_TAG" >> "$GITHUB_OUTPUT"

        '
      env:
        CODER_BASE_IMAGE_TAG: ghcr.io/coder/coder-preview-base:pr${{ steps.pr_info.outputs.PR_NUMBER
          }}
        CODER_IMAGE_TAG: ghcr.io/coder/coder-preview:pr${{ steps.pr_info.outputs.PR_NUMBER
          }}
    - name: Set up kubeconfig
      run: 'set -euo pipefail

        mkdir -p ~/.kube

        echo "${{ secrets.PR_DEPLOYMENTS_KUBECONFIG_BASE64 }}" | base64 --decode >
        ~/.kube/config

        chmod 600 ~/.kube/config

        export KUBECONFIG=~/.kube/config

        '
    - name: Check if the helm deployment already exists
      id: check_deployment
      run: "set -euo pipefail\nif helm status \"pr${PR_NUMBER}\" --namespace \"pr${PR_NUMBER}\"\
        \ > /dev/null 2>&1; then\n  echo \"Deployment already exists. Skipping deployment.\"\
        \n  NEW=false\nelse\n  echo \"Deployment doesn't exist.\"\n  NEW=true\nfi\n\
        echo \"NEW=$NEW\" >> \"$GITHUB_OUTPUT\"\n"
      env:
        PR_NUMBER: ${{ steps.pr_info.outputs.PR_NUMBER }}
    - name: Check changed files
      uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
      id: filter
      with:
        base: ${{ github.ref }}
        filters: "all:\n  - \"**\"\nignored:\n  - \"docs/**\"\n  - \"README.md\"\n\
          \  - \"examples/web-server/**\"\n  - \"examples/monitoring/**\"\n  - \"\
          examples/lima/**\"\n  - \".github/**\"\n  - \"offlinedocs/**\"\n  - \".devcontainer/**\"\
          \n  - \"helm/**\"\n  - \"*[^g][^o][^.][^s][^u][^m]*\"\n  - \"*[^g][^o][^.][^m][^o][^d]*\"\
          \n  - \"*[^M][^a][^k][^e][^f][^i][^l][^e]*\"\n  - \"scripts/**/*[^D][^o][^c][^k][^e][^r][^f][^i][^l][^e]*\"\
          \n  - \"scripts/**/*[^D][^o][^c][^k][^e][^r][^f][^i][^l][^e][.][b][^a][^s][^e]*\"\
          \n"
    - name: Print number of changed files
      run: 'set -euo pipefail

        echo "Total number of changed files: ${ALL_COUNT}"

        echo "Number of ignored files: ${IGNORED_COUNT}"

        '
      env:
        ALL_COUNT: ${{ steps.filter.outputs.all_count }}
        IGNORED_COUNT: ${{ steps.filter.outputs.ignored_count }}
    - name: Build conditionals
      id: build_conditionals
      run: 'set -euo pipefail

        # build if the workflow is manually triggered and the deployment doesn''t
        exist (first build or force rebuild)

        echo "first_or_force_build=${{ (github.event_name == ''workflow_dispatch''
        && steps.check_deployment.outputs.NEW == ''true'') || github.event.inputs.build
        == ''true'' }}" >> "$GITHUB_OUTPUT"

        # build if the deployment already exist and there are changes in the files
        that we care about (automatic updates)

        echo "automatic_rebuild=${{ steps.check_deployment.outputs.NEW == ''false''
        && steps.filter.outputs.all_count > steps.filter.outputs.ignored_count }}"
        >> "$GITHUB_OUTPUT"

        '
  comment-pr:
    needs: get_info
    if: needs.get_info.outputs.BUILD == 'true' || github.event.inputs.deploy == 'true'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e
      with:
        egress-policy: audit
    - name: Find Comment
      uses: peter-evans/find-comment@b30e6a3c0ed37e7c023ccd3f1db5c6c0b0c23aad
      id: fc
      with:
        issue-number: ${{ needs.get_info.outputs.PR_NUMBER }}
        comment-author: github-actions[bot]
        body-includes: ':rocket:'
        direction: last
    - name: Comment on PR
      id: comment_id
      uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ needs.get_info.outputs.PR_NUMBER }}
        edit-mode: replace
        body: '---

          :rocket: Deploying PR ${{ needs.get_info.outputs.PR_NUMBER }} ...

          ---

          '
        reactions: eyes
        reactions-edit-mode: replace
  build:
    needs: get_info
    if: needs.get_info.outputs.BUILD == 'true'
    runs-on: ubuntu-latest
    permissions:
      packages: write
    concurrency:
      group: build-${{ github.workflow }}-${{ github.ref }}-${{ needs.get_info.outputs.BUILD
        }}
      cancel-in-progress: true
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
      CODER_IMAGE_TAG: ${{ needs.get_info.outputs.CODER_IMAGE_TAG }}
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e
      with:
        egress-policy: audit
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Setup Node
      uses: ./.github/actions/setup-node
    - name: Setup Go
      uses: ./.github/actions/setup-go
    - name: Setup sqlc
      uses: ./.github/actions/setup-sqlc
    - name: GHCR Login
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Linux amd64 Docker image
      run: "set -euo pipefail\ngo mod download\nmake gen/mark-fresh\nexport DOCKER_IMAGE_NO_PREREQUISITES=true\n\
        version=\"$(./scripts/version.sh)\"\nCODER_IMAGE_BUILD_BASE_TAG=\"$(CODER_IMAGE_BASE=coder-base\
        \ ./scripts/image_tag.sh --version \"$version\")\"\nexport CODER_IMAGE_BUILD_BASE_TAG\n\
        make -j build/coder_linux_amd64\n./scripts/build_docker.sh \\\n  --arch amd64\
        \ \\\n  --target \"${CODER_IMAGE_TAG}\" \\\n  --version \"$version\" \\\n\
        \  --push \\\n  build/coder_linux_amd64\n"
  deploy:
    needs:
    - build
    - get_info
    if: 'always() && (needs.build.result == ''success'' || needs.build.result == ''skipped'')
      &&

      (needs.get_info.outputs.BUILD == ''true'' || github.event.inputs.deploy == ''true'')

      '
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    env:
      CODER_IMAGE_TAG: ${{ needs.get_info.outputs.CODER_IMAGE_TAG }}
      PR_NUMBER: ${{ needs.get_info.outputs.PR_NUMBER }}
      PR_TITLE: ${{ needs.get_info.outputs.PR_TITLE }}
      PR_URL: ${{ needs.get_info.outputs.PR_URL }}
      PR_HOSTNAME: pr${{ needs.get_info.outputs.PR_NUMBER }}.${{ secrets.PR_DEPLOYMENTS_DOMAIN
        }}
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e
      with:
        egress-policy: audit
    - name: Set up kubeconfig
      run: 'set -euo pipefail

        mkdir -p ~/.kube

        echo "${{ secrets.PR_DEPLOYMENTS_KUBECONFIG_BASE64 }}" | base64 --decode >
        ~/.kube/config

        chmod 600 ~/.kube/config

        export KUBECONFIG=~/.kube/config

        '
    - name: Check if image exists
      run: "set -euo pipefail\nfoundTag=$(\n  gh api /orgs/coder/packages/container/coder-preview/versions\
        \ |\n  jq -r --arg tag \"pr${PR_NUMBER}\" '.[] |\n  select(.metadata.container.tags\
        \ == [$tag]) |\n  .metadata.container.tags[0]'\n)\nif [ -z \"$foundTag\" ];\
        \ then\n  echo \"Image not found\"\n  echo \"${CODER_IMAGE_TAG} not found\
        \ in ghcr.io/coder/coder-preview\"\n  exit 1\nelse\n  echo \"Image found\"\
        \n  echo \"$foundTag tag found in ghcr.io/coder/coder-preview\"\nfi\n"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Add DNS record to Cloudflare
      if: needs.get_info.outputs.NEW == 'true'
      run: "curl -X POST \"https://api.cloudflare.com/client/v4/zones/${{ secrets.PR_DEPLOYMENTS_ZONE_ID\
        \ }}/dns_records\" \\\n  -H \"Authorization: Bearer ${{ secrets.PR_DEPLOYMENTS_CLOUDFLARE_API_TOKEN\
        \ }}\" \\\n  -H \"Content-Type:application/json\" \\\n  --data '{\"type\"\
        :\"CNAME\",\"name\":\"*.'\"${PR_HOSTNAME}\"'\",\"content\":\"'\"${PR_HOSTNAME}\"\
        '\",\"ttl\":1,\"proxied\":false}'\n"
    - name: Create PR namespace
      if: needs.get_info.outputs.NEW == 'true' || github.event.inputs.deploy == 'true'
      run: 'set -euo pipefail

        # try to delete the namespace, but don''t fail if it doesn''t exist

        kubectl delete namespace "pr${PR_NUMBER}" || true

        kubectl create namespace "pr${PR_NUMBER}"

        '
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        persist-credentials: false
    - name: Check and Create Certificate
      if: needs.get_info.outputs.NEW == 'true' || github.event.inputs.deploy == 'true'
      run: "# Using kubectl to check if a Certificate resource already exists\n# we\
        \ are doing this to avoid letsenrypt rate limits\nif ! kubectl get certificate\
        \ \"pr${PR_NUMBER}-tls\" -n pr-deployment-certs > /dev/null 2>&1; then\n \
        \ echo \"Certificate doesn't exist. Creating a new one.\"\n  envsubst < ./.github/pr-deployments/certificate.yaml\
        \ | kubectl apply -f -\nelse\n  echo \"Certificate exists. Skipping certificate\
        \ creation.\"\nfi\necho \"Copy certificate from pr-deployment-certs to pr${PR_NUMBER}\
        \ namespace\"\nuntil kubectl get secret \"pr${PR_NUMBER}-tls\" -n pr-deployment-certs\
        \ &> /dev/null\ndo\n  echo \"Waiting for secret pr${PR_NUMBER}-tls to be created...\"\
        \n  sleep 5\ndone\n(\n  kubectl get secret \"pr${PR_NUMBER}-tls\" -n pr-deployment-certs\
        \ -o json |\n  jq 'del(.metadata.namespace,.metadata.creationTimestamp,.metadata.resourceVersion,.metadata.selfLink,.metadata.uid,.metadata.managedFields)'\
        \ |\n  kubectl -n \"pr${PR_NUMBER}\" apply -f -\n)\n"
    - name: Set up PostgreSQL database
      if: needs.get_info.outputs.NEW == 'true' || github.event.inputs.deploy == 'true'
      run: "helm repo add bitnami https://charts.bitnami.com/bitnami\nhelm install\
        \ coder-db bitnami/postgresql \\\n  --namespace \"pr${PR_NUMBER}\" \\\n  --set\
        \ image.repository=bitnamilegacy/postgresql \\\n  --set auth.username=coder\
        \ \\\n  --set auth.password=coder \\\n  --set auth.database=coder \\\n  --set\
        \ persistence.size=10Gi\nkubectl create secret generic coder-db-url -n \"\
        pr${PR_NUMBER}\" \\\n  --from-literal=url=\"postgres://coder:coder@coder-db-postgresql.pr${PR_NUMBER}.svc.cluster.local:5432/coder?sslmode=disable\"\
        \n"
    - name: Create a service account, role, and rolebinding for the PR namespace
      if: needs.get_info.outputs.NEW == 'true' || github.event.inputs.deploy == 'true'
      run: 'set -euo pipefail

        # Create service account, role, rolebinding

        envsubst < ./.github/pr-deployments/rbac.yaml | kubectl apply -f -

        '
    - name: Create values.yaml
      env:
        EXPERIMENTS: ${{ github.event.inputs.experiments }}
        PR_DEPLOYMENTS_GITHUB_OAUTH_CLIENT_ID: ${{ secrets.PR_DEPLOYMENTS_GITHUB_OAUTH_CLIENT_ID
          }}
        PR_DEPLOYMENTS_GITHUB_OAUTH_CLIENT_SECRET: ${{ secrets.PR_DEPLOYMENTS_GITHUB_OAUTH_CLIENT_SECRET
          }}
      run: 'set -euo pipefail

        envsubst < ./.github/pr-deployments/values.yaml > ./pr-deploy-values.yaml

        '
    - name: Install/Upgrade Helm chart
      run: 'set -euo pipefail

        helm dependency update --skip-refresh ./helm/coder

        helm upgrade --install "pr${PR_NUMBER}" ./helm/coder \

        --namespace "pr${PR_NUMBER}" \

        --values ./pr-deploy-values.yaml \

        --force

        '
    - name: Install coder-logstream-kube
      if: needs.get_info.outputs.NEW == 'true' || github.event.inputs.deploy == 'true'
      run: "helm repo add coder-logstream-kube https://helm.coder.com/logstream-kube\n\
        helm upgrade --install coder-logstream-kube coder-logstream-kube/coder-logstream-kube\
        \ \\\n  --namespace \"pr${PR_NUMBER}\" \\\n  --set url=\"https://${PR_HOSTNAME}\"\
        \n"
    - name: Get Coder binary
      if: needs.get_info.outputs.NEW == 'true' || github.event.inputs.deploy == 'true'
      run: "set -euo pipefail\n\nDEST=\"${HOME}/coder\"\nURL=\"https://${PR_HOSTNAME}/bin/coder-linux-amd64\"\
        \n\nmkdir -p \"$(dirname \"$DEST\")\"\n\nCOUNT=0\nuntil curl --output /dev/null\
        \ --silent --head --fail \"$URL\"; do\n    printf '.'\n    sleep 5\n    COUNT=$((COUNT+1))\n\
        \    if [ \"$COUNT\" -ge 60 ]; then\n      echo \"Timed out waiting for URL\
        \ to be available\"\n      exit 1\n    fi\ndone\n\ncurl -fsSL \"$URL\" -o\
        \ \"${DEST}\"\nchmod +x \"${DEST}\"\n\"${DEST}\" version\nsudo mv \"${DEST}\"\
        \ /usr/local/bin/coder\n"
    - name: Create first user
      if: needs.get_info.outputs.NEW == 'true' || github.event.inputs.deploy == 'true'
      id: setup_deployment
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: "set -euo pipefail\n\n# create a masked random password 12 characters long\n\
        password=$(openssl rand -base64 16 | tr -d \"=+/\" | cut -c1-12)\n\n# add\
        \ mask so that the password is not printed to the logs\necho \"::add-mask::$password\"\
        \necho \"password=$password\" >> \"$GITHUB_OUTPUT\"\n\ncoder login \\\n  --first-user-username\
        \ \"pr${PR_NUMBER}-admin\" \\\n  --first-user-email \"pr${PR_NUMBER}@coder.com\"\
        \ \\\n  --first-user-password \"$password\" \\\n  --first-user-trial=false\
        \ \\\n  --use-token-as-session \\\n  \"https://${PR_HOSTNAME}\"\n\n# Create\
        \ a user for the github.actor\n# TODO: update once https://github.com/coder/coder/issues/15466\
        \ is resolved\n# coder users create \\\n#   --username ${GITHUB_ACTOR} \\\n\
        #   --login-type github\n\n# promote the user to admin role\n# coder org members\
        \ edit-role ${GITHUB_ACTOR} organization-admin\n# TODO: update once https://github.com/coder/internal/issues/207\
        \ is resolved\n"
    - name: Send Slack notification
      if: needs.get_info.outputs.NEW == 'true' || github.event.inputs.deploy == 'true'
      run: "curl -s -o /dev/null -X POST -H 'Content-type: application/json' \\\n\
        \  -d \\\n  '{\n    \"pr_number\": \"'\"${PR_NUMBER}\"'\",\n    \"pr_url\"\
        : \"'\"${PR_URL}\"'\",\n    \"pr_title\": \"'\"${PR_TITLE}\"'\",\n    \"pr_access_url\"\
        : \"'\"https://${PR_HOSTNAME}\"'\",\n    \"pr_username\": \"'\"pr${PR_NUMBER}-admin\"\
        '\",\n    \"pr_email\": \"'\"pr${PR_NUMBER}@coder.com\"'\",\n    \"pr_password\"\
        : \"'\"${PASSWORD}\"'\",\n    \"pr_actor\": \"'\"${GITHUB_ACTOR}\"'\"\n  }'\
        \ \\\n  ${{ secrets.PR_DEPLOYMENTS_SLACK_WEBHOOK }}\necho \"Slack notification\
        \ sent\"\n"
      env:
        PASSWORD: ${{ steps.setup_deployment.outputs.password }}
    - name: Find Comment
      uses: peter-evans/find-comment@b30e6a3c0ed37e7c023ccd3f1db5c6c0b0c23aad
      id: fc
      with:
        issue-number: ${{ env.PR_NUMBER }}
        comment-author: github-actions[bot]
        body-includes: ':rocket:'
        direction: last
    - name: Comment on PR
      uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9
      env:
        STATUS: ${{ needs.get_info.outputs.NEW == 'true' && 'Created' || 'Updated'
          }}
      with:
        issue-number: ${{ env.PR_NUMBER }}
        edit-mode: replace
        comment-id: ${{ steps.fc.outputs.comment-id }}
        body: '---

          :heavy_check_mark: PR ${{ env.PR_NUMBER }} ${{ env.STATUS }} successfully.

          :rocket: Access the credentials [here](${{ secrets.PR_DEPLOYMENTS_SLACK_CHANNEL_URL
          }}).

          ---

          cc: @${{ github.actor }}

          '
        reactions: rocket
        reactions-edit-mode: replace
    - name: Create template and workspace
      if: needs.get_info.outputs.NEW == 'true' || github.event.inputs.deploy == 'true'
      run: 'set -euo pipefail

        cd .github/pr-deployments/template

        coder templates push -y --variable "namespace=pr${PR_NUMBER}" kubernetes


        # Create workspace

        coder create --template="kubernetes" kube --parameter cpu=2 --parameter memory=4
        --parameter home_disk_size=2 -y

        coder stop kube -y

        '
