name: weekly-docs
on:
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  check-docs:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e
      with:
        egress-policy: audit
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        persist-credentials: false
    - name: Check Markdown links
      uses: umbrelladocs/action-linkspector@652f85bc57bb1e7d4327260decc10aa68f7694c3
      id: markdown-link-check
      with:
        reporter: github-pr-review
        config_file: .github/.linkspector.yml
        fail_on_error: true
        filter_mode: file
    - name: Send Slack notification
      if: failure() && github.event_name == 'schedule'
      run: "curl \\\n  -X POST \\\n  -H 'Content-type: application/json' \\\n  -d\
        \ '{\"msg\":\"Broken links found in the documentation. Please check the logs\
        \ at '\"${LOGS_URL}\"'\"}' \"${{ secrets.DOCS_LINK_SLACK_WEBHOOK }}\"\necho\
        \ \"Sent Slack notification\"\n"
      env:
        LOGS_URL: https://github.com/coder/coder/actions/runs/${{ github.run_id }}
